### ISSUE TITLE
Use prepareDataTokeList() function from Datax.js 

### ISSUE THREAD

**Issue by keithfrazier98** [dataxfi/scripts#16]
The function [prepareDataTokeList()](https://github.com/dataxfi/scripts/blob/0bd82228902f976f70fc7bdf8daa85cefcd9c009/src/AutoUpdateTokens.ts#L118) is redefined in the scripts and could be used directly from datax.js as a dep.

**Comment by 0xrishabh** [comment]
Do you think adding a dependency, just for one simple function would make sense?

**Comment by akankshapatel30** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scripts repo issues](https://trello.com/c/AA3kHdQI/2-scripts-repo-issues)

**Comment by innoprenuer** [comment]
We are not adding any new dependencies here. Lets keep it open and public, so others can use these lists in their dapps too.
